/*MOSTRA TODOS OS CAMPOS DA TABELA DEPARTAMENTO*/
SELECT * FROM DEPARTAMENTO;

/*DESC OU DESCRIBE DEPARTAMENTO MOSTRA A ESTRUTURA DA TABELA*/
DESC DEPARTAMENTO; 

/* CTRL + ENTER PARA EXECUTAR O COMANDO SQL NO ORACLE SQL DEVELOPER */

/*AUMENTA O NÚMERO DE LINHAS (HEIGHT)*/
SET PAGESIZE; 

/*AUMENTA O NÚMERO DE COLUNAS A DIREITA (WIDTH)*/
SET LINESIZE;

ALTER TABLE EMPREGADO MODIFY NAME_EMP VARCHAR(55);
ALTER TABLE DEPARTAMENTO MODIFY LOCALIZ VARCHAR2(70);
ALTER TABLE "SYSTEM"."DEPARTAMENTO" RENAME COLUMN "DEPTNUM" TO "DEPTNO";

/*O ORACLE SQL DEVELOPER ACEITA ESSE CARACETER º. O SQL PLUS NÃO ACEITA ESSE CARACTER º*/
SELECT NAME_EMP NOME, SALARIO, DEPTNUM Nº_DEPARTAMENTO FROM EMPREGADO WHERE HIREDATE LIKE '%87%';

SELECT NAME_EMP NOME_FUNCIONARIO, SALARIO "REMUNERAÇÃO", DEPTNUM Nº_DEPARTAMENTO
FROM EMPREGADO WHERE HIREDATE LIKE '%81%';

SELECT NAME_EMP, JOB, SALARIO FROM EMPREGADO ORDER BY JOB, NAME_EMP;

SELECT NAME_EMP nome, JOB cargo, salario, TO_CHAR(hiredate,'dd/month/yyyy') data
FROM empregado;

SELECT NAME_EMP NOME_DO_FUNCIONARIO, JOB FUNCAO, SALARIO, TO_CHAR(HIREDATE,'DD/MONTH/YYYY') DATA
FROM EMPREGADO WHERE HIREDATE LIKE '%81%';

/*PREENCHENDO POR PARAMETROS */
INSERT INTO DEPARTAMENTO
VALUES(&DEPTNUM, '&DEPTNAME', '&LOCALIZ');

COMMIT WORK;

SELECT NAME_EMP "NOME DO FUNCIONÁRIO", JOB CARGO, SALARIO "SALÁRIO", DEPTNUM "Nº DO DEPARTAMENTO", 
TO_CHAR(HIREDATE,'DD/MONTH/YYYY') "DATA ADMISSÃO", (SYSDATE-HIREDATE)/7 "SEMANAS DE VÍNCULO"
FROM EMPREGADO WHERE HIREDATE LIKE '%81%' ORDER BY JOB DESC, NAME_EMP;

SELECT DEPTNUM "Nº DO DEPARTAMENTO", MIN(SALARIO) "MENOR SALÁRIO", MAX(SALARIO) "MAIOR SALÁRIO", AVG(SALARIO) "MÉDIA SALARIAL"
FROM EMPREGADO GROUP BY DEPTNUM;

CREATE TABLE COPIA_DEPARTAMENTO AS SELECT * FROM DEPARTAMENTO;

DROP TABLE COPIA_DEPARTAMENTO;

CREATE TABLE COPIA_EMPREGADO AS SELECT * FROM EMPREGADO;

DROP TABLE COPIA_EMPREGADO;

SELECT DEPTNUM "NÚMERO DO DEPARTAMENTO", COUNT(DEPTNUM) "QUANT. DE FUNCIONÁRIOS"
FROM EMPREGADO GROUP BY DEPTNUM;

SELECT DEPTNUM "NÚMERO DO DEPARTAMENTO", SUM(SALARIO) "TOTAL DE SALÁRIOS"
FROM EMPREGADO GROUP BY DEPTNUM;

SELECT DEPTNUM Nº_DO_DEPARTAMENTO, MIN(SALARIO) "MENOR SALÁRIO", MAX(SALARIO) "MAIOR SALÁRIO", 
AVG(SALARIO) "MÉDIA SALARIAL" FROM EMPREGADO GROUP BY DEPTNUM;

SELECT DEPTNUM "NÚMERO DO DEPARTAMENTO", COUNT(DEPTNUM) "QUANT. DE FUNCIONÁRIOS"
FROM EMPREGADO GROUP BY DEPTNUM;

SELECT DEPTNUM "NÚMERO DO DEPARTAMENTO", SUM(SALARIO) "TOTAL DE SALÁRIOS"
FROM EMPREGADO GROUP BY DEPTNUM;

SELECT SUM(SALARIO) "TOTAL DE SALÁRIOS DA EMPRESA" FROM EMPREGADO;

SELECT DEPTNUM "NÚMERO DO DEPARTAMENTO", SUM(SALARIO) "TOTAL DE SALÁRIOS"
FROM EMPREGADO GROUP BY DEPTNUM;

/*COMANDO PARA DELETAR LINHA DA TABELA*/
DELETE EMPREGADO WHERE HIREDATE LIKE '%87';
