/*APAGAR A TABELA EMPREGADO E A RESTRICAO EM CASCATA*/
DROP TABLE EMPREGADO CASCADE CONSTRAINT;

/*APAGAR A TABELA DEPARTAMENTO E A RESTRICAO EM CASCATA*/
DROP TABLE DEPARTAMENTO CASCADE CONSTRAINT;
