/*MOSTRA TODOS OS CAMPOS DA TABELA EMPREGADO*/
SELECT * FROM EMPREGADO;

SELECT NAME_EMP, SALARIO FROM EMPREGADO WHERE SALARIO <= 3500
/

SELECT NAME_EMP NOME_FUNCIONARIO, SALARIO REMUNERACAO FROM EMPREGADO WHERE SALARIO = 5000
/

SELECT NAME_EMP "NOME DO FUNCIONÁRIO", SALARIO "SALÁRIO MENSAL"
FROM EMPREGADO WHERE SALARIO >=5000
/

SELECT DISTINCT JOB CARGOS FROM EMPREGADO;

SELECT DEPTNAME NOME_DEPARTAMENTO FROM DEPARTAMENTO WHERE DEPTNUM = 30
/

UPDATE EMPREGADO SET SALARIO = 5500 WHERE NAME_EMP = 'SMITH'
/

UPDATE EMPREGADO SET MGR = 7800 WHERE NAME_EMP = 'ANTONOIO'
/

UPDATE EMPREGADO SET NAME_EMP = 'ANTONIO' WHERE NAME_EMP = 'ANTONOIO'
/

UPDATE EMPREGADO SET MGR = 7888 WHERE NUM_EMP = 7800
/

SELECT NAME_EMP "NOME DO FUNCIONÁRIO", SALARIO "SALÁRIO", DEPTNUM "NÚMERO DO DEPARTAMENTO",
HIREDATE DATA_ADMISSAO FROM EMPREGADO WHERE HIREDATE LIKE '%81%'
/

SELECT NAME_EMP "NOME DO FUNCIONÁRIO", JOB CARGO, SALARIO "SALÁRIO"
FROM EMPREGADO ORDER BY SALARIO
/

SELECT NAME_EMP "NOME DO FUNCIONÁRIO", JOB CARGO, SALARIO "SALÁRIO"
FROM EMPREGADO ORDER BY NAME_EMP
/

/*LIMPA O PROMPT DE COMANDOS*/
CL SCR

/*MOSTRA O MÊS POR EXTENSO*/
SELECT NAME_EMP "Nome do Funcionário", JOB Cargo, SALARIO Salario,
TO_CHAR(HIREDATE,'DD/MONTH/YYYY') "Data de Admissão" FROM EMPREGADO;

/*MOSTRA O MÊS EM NÚMEROS*/
SELECT NAME_EMP "Nome do Funcionário", JOB Cargo, SALARIO Salario,
TO_CHAR(HIREDATE,'DD/MM/YYYY') "Data de Admissão" FROM EMPREGADO;

ALTER TABLE EMPREGADO MODIFY NAME_EMP VARCHAR(45)
/

SELECT NAME_EMP "NOME DO FUNCIONÁRIO", JOB CARGO, SALARIO SALARIO,
TO_CHAR(HIREDATE,'DD/Month/YYYY') "DATA DE ADMISSÃO" FROM EMPREGADO
WHERE HIREDATE LIKE '%87%';

SELECT NAME_EMP "NOME DO EMPREGADO", JOB CARGO, SALARIO "SALÁRIO" 
FROM EMPREGADO ORDER BY JOB, NAME_EMP;

SELECT NAME_EMP "NOME DO FUNCIONÁRIO", JOB CARGO, SALARIO,
TO_CHAR(HIREDATE,'DD/Month/YYYY') "DATA DE ADMISSÃO", 
TO_CHAR(SYSDATE,'DD/MONTH/YYYY') "DATA DE HOJE",
(SYSDATE-HIREDATE)/7 "SEMANAS DE VÍNCULO" FROM EMPREGADO WHERE HIREDATE LIKE '%87%';

SELECT DEPTNUM "NÚMERO DO DEPARTAMENTO", MIN(SALARIO) "MENOR SALÁRIO",
MAX(SALARIO) "MAIOR SALÁRIO", AVG(SALARIO) "MÉDIA SALARIAL" FROM EMPREGADO GROUP BY DEPTNUM;

SELECT NAME_EMP "NOME DO FUNCIONÁRIO", JOB CARGO, SALARIO "SALÁRIO",
TO_CHAR(HIREDATE,'DD/Month/YYYY') "DATA DE ADMISSÃO", 
TO_CHAR(SYSDATE,'DD/MONTH/YYYY') "DATA DE HOJE",
(SYSDATE-HIREDATE)/7 "SEMANAS DE VÍNCULO" FROM EMPREGADO WHERE HIREDATE LIKE '%81%';

CREATE TABLE COPIA_DEPARTAMENTO AS SELECT * FROM DEPARTAMENTO;

DROP TABLE COPIA_DEPARTAMENTO;

SELECT DEPTNUM "Nº DO DEPARTAMENTO", COUNT(NUM_EMP) "QUANT. DE FUNCIONÁRIOS"
FROM EMPREGADO GROUP BY DEPTNUM;

SELECT DEPTNUM "Nº DO DEPARTAMENTO", COUNT(NUM_EMP) "QUANT. DE FUNCIONÁRIOS",
SUM(SALARIO) "SOMA SALARIAL" FROM EMPREGADO GROUP BY DEPTNUM;

SELECT D.DEPTNAME "NOME DO DEPARTAMENTO", SUM(SALARIO) "SOMA DE TODOS SALÁRIOS"
FROM EMPREGADO E INNER JOIN DEPARTAMENTO D ON E.DEPTNUM = D.DEPTNUM
WHERE SALARIO > 3500 GROUP BY D.DEPTNAME HAVING SUM(SALARIO) > 8500 ORDER BY D.DEPTNAME
/

/*AUMENTA O NÚMERO DE LINHAS (HEIGHT)*/
SET PAGESIZE; 

/*AUMENTA O NÚMERO DE COLUNAS A DIREITA (WIDTH)*/
SET LINESIZE;

SELECT DEPTNUM "Nº DO DEPARTAMENTO", NAME_EMP "FUNCIONÁRIO", SALARIO "MAIORES SALÁRIOS"
FROM EMPREGADO WHERE (DEPTNUM, SALARIO) IN (SELECT DEPTNUM, MAX(SALARIO)
FROM EMPREGADO GROUP BY DEPTNUM);

SELECT JOB CARGOS, SUM(SALARIO) "TOTAL DE SALÁRIOS"
FROM EMPREGADO GROUP BY JOB ORDER BY JOB
/

SELECT CONSTRAINT_NAME "NOME DA RESTRIÇÃO", CONSTRAINT_TYPE "TIPO DA RESTRIÇÃO",
SEARCH_CONDITION "CONDIÇÃO" FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'PAGAMENTO'
/

SELECT * FROM EMPREGADO WHERE NAME_EMP = 'SMITH' OR NAME_EMP = 'TURNER'
/

SELECT * FROM EMPREGADO WHERE NAME_EMP = 'SMITH' OR NAME_EMP = 'TYNNA'
/

/*Vai dar erro*/
SELECT JOB, AVG(SALARIO) FROM EMPREGADO
/

/*Vai dar erro*/
SELECT JOB, SALARIO, AVG(SALARIO) FROM EMPREGADO GROUP BY JOB;

/*Assim não dá erro*/
SELECT JOB, AVG(SALARIO) FROM EMPREGADO GROUP BY JOB;

UPDATE EMPREGADO SET SALARIO = 4000 WHERE NAME_EMP = 'MILLER'
/

UPDATE EMPREGADO SET DEPTNUM = 40 WHERE NAME_EMP = 'SMITH'
/

SELECT DEPTNUM "Nº DO DEPARTAMENTO", COUNT(*), ROUND(AVG(SALARIO),2) "MÉDIA SALARIAL"
FROM EMPREGADO GROUP BY DEPTNUM;

SELECT DEPTNUM "Nº DO DEPARTAMENTO", JOB CARGO, MAX(SALARIO) "MAIOR SALÁRIO",
MIN(SALARIO) "MENOR SALÁRIO", SUM(SALARIO) "SOMA SALARIAL"
FROM EMPREGADO GROUP BY (DEPTNUM, JOB) ORDER BY DEPTNUM
/

/*COMANDO PARA DELETAR LINHA DA TABELA*/
DELETE EMPREGADO WHERE HIREDATE LIKE '%87'
/
DELETE EMPREGADO WHERE HIREDATE LIKE '%81'
/

UPDATE EMPREGADO SET DEPTNUM = 
(SELECT DEPTNUM FROM DEPARTAMENTO WHERE DEPTNAME = 'ACCOUNTING') WHERE NAME_EMP = 'JAMES'
/

SELECT NAME_EMP "FUNCIONÁRIO", NUM_EMP "CÓD. FUNCIONÁRIO", SALARIO "SALÁRIO", COMISSAO "COMISSÃO"
FROM EMPREGADO WHERE COMISSAO IS NULL OR COMISSAO = 0 ORDER BY NAME_EMP DESC
/

COMMIT WORK;

/*MOSTRA TODAS AS TABELAS DO BANCO DE DADOS*/
SELECT * FROM CAT;

ROLLBACK
/


















