INSERT INTO DEPARTAMENTO(DEPTNUM, DEPTNAME, LOCALIZ)
VALUES(10 , 'ACCOUNTING', 'NEW YORK');

INSERT INTO DEPARTAMENTO(DEPTNUM, DEPTNAME, LOCALIZ)
VALUES(20 , 'RESEARCH', 'DALLAS');

INSERT INTO DEPARTAMENTO(DEPTNUM, DEPTNAME, LOCALIZ)
VALUES(50, 'ORCAMENTO', 'SAO PAULO');

/*SE PREENCHER TODOS OS CAMPOS, NAO PRECISA DECLARAR OS NOMES DAS COLUNAS */
INSERT INTO DEPARTAMENTO
VALUES(30 , 'SALES', 'CHICAGO');

INSERT INTO DEPARTAMENTO
VALUES(40 , 'OPERATIONS', 'BOSTON');

COMMIT;

/*PREENCHENDO POR PARAMETROS */
INSERT INTO DEPARTAMENTO 
VALUES(&DEPTNUM, '&DEPTNAME', '&LOCALIZ');

